version: '3.9'
services:
  postgres:
    platform: linux/x86_64
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: